[package]
name = "oscanity"
version = "0.2.0"
authors = ["Stephen Buchanan <stephen.buchanan@random.studio>"]
description = "Lightweight command-line tools for sending and receiving OSC messages"
license = "MIT"
edition = "2021"

[dependencies]
rosc = "~0.1"
