# https://rust-lang.github.io/rustfmt/

# Edition

edition = "2018"

# Stable

newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

# Nightly

# condense_wildcard_suffixes = true
# format_strings = true
# match_block_trailing_comma = true
# merge_imports = true
# normalize_comments = true
# reorder_impl_items = true
# report_fixme = "Always"
# report_todo = "Always"
# spaces_around_ranges = true
# wrap_comments = true
